app:
  locale: en_US
  timeZone: Asia/Shanghai
  data:
    path: "~"

spring:
  application:
    name:   slackerDBService
  task:
    scheduling:
      pool:
        size: 10

# spring boot 端口配置
server:
  port: 9443
  #开启优雅停机，默认IMMEDIATE，立即停机
  shutdown: graceful

# 日志文件配置
logging:
  config: classpath:logback-spring.xml
  file:
    path: ./log

# swagger开关
swagger:
  enable: false